In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df_lending = pd.read_csv("Resources/lending_data.csv")

# Review the DataFrame
df_lending.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [4]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df_lending["loan_status"]

# Separate the X variable, the features
X = df_lending.drop(columns = "loan_status")

In [6]:
# Review the y variable Series
y[:]

0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64

In [7]:
# Review the X variable DataFrame
X.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [16]:
# Check the balance of our target values
y.value_counts(ascending = True)

1     2500
0    75036
Name: loan_status, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [11]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [46]:
# Code based on in-class activity 20.1.4
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Code based on in-class activity 20.1.4
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
classifier = LogisticRegression(solver = "lbfgs", random_state = 1)
classifier

LogisticRegression(random_state=1)

In [47]:
# Code based on in-class activity 20.1.4
# Fit the model using training data
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [48]:
# Code based on in-class activity 20.1.4
# Get the training and testing data scores
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9921240885954051
Testing Data Score: 0.9918489475856377


### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [49]:
# Make a prediction using the testing data
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

Prediction  Actual
60914           0       0
36843           0       0
1966            0       0
70137           0       0
27237           0       0
...           ...     ...
45639           0       0
11301           0       0
51614           0       0
4598            0       0
2793            0       0

[19384 rows x 2 columns]

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [50]:
# Print the balanced_accuracy score of the model
balanced_accuracy_score(y_test, predictions)

0.9520479254722232

In [51]:
# Code from in-class activity 20.1.6 and class lecture
# Generate training predictions
training_predictions = lr_model.predict(X_train)

# Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

In [52]:
# Code from in-class activity 20.1.6 
# Generate a confusion matrix for the model
# For the training
training_matrix = confusion_matrix(y_train, training_predictions)
print(training_matrix)

[[55994   277]
 [  181  1700]]


In [53]:
# Code from in-class activity 20.1.6 
# Generate a confusion matrix for the model
# For the testing
testing_matrix = confusion_matrix(y_test, testing_predictions)
print(testing_matrix)

[[18663   102]
 [   56   563]]


In [54]:
# Code from in-class activity 20.1.6 
# Print the classification report for the model
# For training
training_report = classification_report(y_train, training_predictions)
print(training_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56271
           1       0.86      0.90      0.88      1881

    accuracy                           0.99     58152
   macro avg       0.93      0.95      0.94     58152
weighted avg       0.99      0.99      0.99     58152



In [55]:
# Code from in-class activity 20.1.6
# Print the classification report for the model
# For testing
testing_report = classification_report(y_test, testing_predictions)
print(testing_report)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:**  Looking at the two classification reports for the training and test data, it looks as if model performance remained  stable with nominal changes between the training and test data. This is the anticipated outcome: the model is performing well on data it hasn't seen before. Since we're getting strong precision and recall on the test dataset, this is a good indication that the model will perform well in real life.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [57]:
# Code based on RandomOverSampler documentation: https://imbalanced-learn.org/stable/references/generated/imblearn.over_sampling.RandomOverSampler.html
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler
from collections import Counter
from sklearn.datasets import make_classification

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
random_over_sampler_model = RandomOverSampler(random_state = 1)

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = random_over_sampler_model.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 56271, 1: 56271})

In [58]:
# Count the distinct values of the resampled labels data
y_resampled.value_counts(ascending = True)

0    56271
1    56271
Name: loan_status, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [61]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model = LogisticRegression(random_state = 1)

# Fit the model using the resampled training data
model.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
testing_predictions = model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [62]:
# Print the balanced_accuracy score of the model 
predictions = classifier.predict(X_resampled)
balanced_accuracy_score(y_resampled, predictions)

0.9494055552593699

In [63]:
# Generate a confusion matrix for the model
confusion_matrix = confusion_matrix(y_resampled, predictions)
print(confusion_matrix)

[[55994   277]
 [ 5417 50854]]


In [64]:
# Print the classification report for the model
class_report = classification_report(y_resampled, predictions)
print(class_report)

              precision    recall  f1-score   support

           0       0.91      1.00      0.95     56271
           1       0.99      0.90      0.95     56271

    accuracy                           0.95    112542
   macro avg       0.95      0.95      0.95    112542
weighted avg       0.95      0.95      0.95    112542



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model, fit with oversampled data, shows a decrease in performance as compared to the logistic regression model fit with the original data.  